#!/usr/bin/env node

if (process.argv.length < 4) {
    console.log('Syntax: ' + process.argv[1] + ' <solution> <input>');
    process.exit(1);
}

const lines = require('fs').readFileSync(process.argv[3], 'utf8').split('\n');
if (lines[lines.length-1] === '') lines.pop();

const Solution = require('./' + process.argv[2]);

new Solution(lines).run();
